services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: coutts99/docker-fleet-backend:latest
    platforms:
      - linux/amd64
      - linux/arm64

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: coutts99/docker-fleet-frontend:latest
    platforms:
      - linux/amd64
      - linux/arm64
